trigger: none
pr: none

stages:
  - stage: deploy
    displayName: deploy:production
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: production
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
        pool:
          vmImage: "ubuntu-latest"
        environment: production
        variables:
          - group: shared
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - checkout: self
                  persistCredentials: true
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '3.8'
                    addToPath: true
                    architecture: 'x64'
                - task: TwineAuthenticate@1
                  displayName: 'Authenticate'
                  inputs:
                    pythonUploadServiceConnection: 'PyPI - production - middleware'
                - script: |
                    # Return immediately on any error and print error output to standard error output.
                    set -ev

                    BASEDIR=$PWD

                    # Ensure that we have the latest versions of Twine, Wheel, and Setuptools.
                    python -m pip install --upgrade twine wheel setuptools

                    # Build the distributions.
                    for dir in src/*/ ; do
                      pushd .
                      cd "$dir"
                      python setup.py bdist_wheel --dist-dir "$BASEDIR/dist/"
                      popd
                    done

                    # Upload the distributions.
                    for package in dist/* ; do
                      twine upload --repository proofdock-chaos-middleware --config-file $(PYPIRC_PATH) --skip-existing $package
                    done
                  displayName: 'Upload packages'
                - script: |
                    # Return immediately on any error and print error output to standard error output.
                    set -ev

                    BASEDIR=$PWD

                    # Collect the documentation pages.
                    mkdir -p "$BASEDIR/docs" && cp README.md "$BASEDIR/docs"
                    mkdir -p "$BASEDIR/docs/core" && cp src/core/README.md "$BASEDIR/docs/core"
                    mkdir -p "$BASEDIR/docs/flask" && cp src/contrib-flask/README.md "$BASEDIR/docs/flask"
                    mkdir -p "$BASEDIR/docs/django" && cp src/contrib-django/README.md "$BASEDIR/docs/django"
                  displayName: 'Collect documentation pages'
                - task: PublishPipelineArtifact@1
                  inputs:
                    targetPath: "docs"
                    artifactName: "chaos-middleware-python-docs"
