name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Prepare checks
        run: |
          python -m pip install -r requirements-dev.txt
          python -m pip install src/core
          python -m pip install src/contrib-flask
          python -m pip install src/contrib-django
      - name: Check code style
        run: flake8 src/
      - name: Run tests
        run: python -m pytest
      - uses: codecov/codecov-action@v1
        with:
          file: ./tests/.results/coverage.xml
